### ISSUE TITLE
SQL Converion 함수 연결

### ISSUE THREAD

**Issue by kalipso** [wjjeong/SQLCV#3]
대부분의 기능은 완료되었습니다.
SQLConversion.py에 doSqlConversion 함수에서 file_nm, sql_id를 넘겨서 Conversion을 실행하면 되는데, 정원준 선임이 작성한 함수 파일 및 호출 방법 알려주세요.

**Comment by wjjeong** [comment]
넵넵 지금까지 개발한 소스 올려놓을게요

**Comment by wjjeong** [comment]
SqlConvLoging.py 를 추가했습니다. 해당 파일 import후 아래 함수 사용하시면 됩니다.

run_sc('ZhnSql.xml' ,'getJuminInfo')
