### ISSUE TITLE
SQL Conversion 에러 확인 요청

### ISSUE THREAD

**Issue by kalipso** [wjjeong/SQLCV#4]
![2017-08-08 16 56 30](https://user-images.githubusercontent.com/1968934/29062138-7842c8c0-7c5b-11e7-8fee-bc3ebd73447f.PNG)

SQL 컨버전 함수 연결 및 ProgressBar 연결했습니다.
다만 제 PC에서는 컨버전 실행 시 첨부한 이미지와 같이 에러가 발생하고 있습니다. (난 데이터구조 변경 안했음)

1. 정선임 PC에서 에러가 발생하지 않는지 확인 해주세요.
2. 데이터 구조 변경 시 데이터가 없기 때문에 테스트하기가 어렵습니다. 데이터 구조 변경에 따른 데이터도 같이 주세요. 
3. 2번이 힘들다면,. 같이 공유할 수 있는 PostgreSQL 서버가 있으면 더더 좋겠네요^^

더운 날씨에 몸들 건강하시고~

**Comment by wjjeong** [comment]
제 로컬에서는 잘되네요~ PostgreSQLPortable.zip 파일을 구글드라이브에 올려두었습니다. 일단 압축풀어서 사용하시면 되구요, 공용서버구축은 조금더 확인해볼께요~

**Comment by kalipso** [comment]
이 문제는 소문자가 변환되지 않는 문제였음. 입력 시 UPPERCASE로 변경하여 해결함.
