### ISSUE TITLE
SQL 컨버전이 잘 안되는 것 같음..

### ISSUE THREAD

**Issue by kalipso** [wjjeong/SQLCV#5]
오랜만에 정선임이 올린 DB를 다운받아서 테스트를 하고 있는데.. 오류인 것 같아서 이슈로 올립니다.

**1. "SQL정보 > SQL변환" 메뉴에서 아래 SQL파일 업로드**
[SQLUploadSample.zip](https://github.com/wjjeong/SQLCV/files/1331811/SQLUploadSample.zip)

**2. 아래 2개 SQL을 컨버전 하였음**
* samplesql1.xml > selGvofMs
* samplesql2.xml	selGvofChgHs

**3. 아래와 같은 문제가 확인되었음.** 
  1) B2EN_SC_SQL_LIST의 wk_stat_cd가 R --> C로 변경되어야 하나 변경되지 않음
      (AP에서 완료되면 변경해줘야 하는지 확인 바람)
  2) B2EN_SC_SQL_TEXT_RST에는 아래와 같은 엉뚱한 쿼리가 입력됨
SELECT
     -- ZhnSql.xml : getJuminInfo
        'A'     AS FLG
      , KOR_FULNM
      , /* SC - ZHMA_JUMIN_NO : No Mapping Info*/                       
    FROM  RS_RSDT_MS /* SC 테이블 중복확인 : RS_RSDT_MS,RS_PSNL_DSC_MS,RS_RSDT_HS,RS_PSNL_DSC_HS */ TZM
   WHERE  TZM.DAT_MTCH_CL_CD IN('0', '1', '3', '4')
union all
  3) 매핑정보를 입력하려고 했으나 제대로 입력되지 않음(엑셀을 만들어서 넣었으나 응답이 없음)

위 에러들에 대해서 확인하고, 어떤 문제인지 알려주세요. 필요하면 SQLConversion.py도 수정하겠음.

**Comment by kalipso** [comment]
아 잠시만.. git update를 안했었는데, 지금 확인해보니 3-1)과 2)는 update후에 잘 되네.

**Comment by kalipso** [comment]
다시.. 위에꺼는 무시하고.. 

엉뚱한 쿼리가 입력되는 에러는 없어졌는데, 매핑정보를 입력하고 컨버전을 실행하였으나(혹시 몰라서 B2EN_SQL_TEXT_RST 데이터 삭제) 아래와 같이 입력됨..

select *
from
 
where
 /* SC - GVOF_CD : No Mapping Info*/ = 'P014231'

**Comment by kalipso** [comment]
테스트한 파일을 업로드할테니 참고하세요~
[테스트파일.zip](https://github.com/wjjeong/SQLCV/files/1331848/default.zip)

**Comment by wjjeong** [comment]
제가 테스트해봤는데요, 매핑정보를 소문자로 넣었을 경우 처리가 안되네요. 이건 매핑정보 입력할 때(화면입력 or 엑셀입력) 대문자로 변환해서 넣어야 할듯합니다.  대문자로 변경하면 정상적으로 변환이 됩니다.

**Comment by wjjeong** [comment]
책임님 여유가 있으시면.. 소스수정 좀 해주세요 ㅎㅎ

**Comment by kalipso** [comment]
음 그렇구만.. 내가 수정할께. 엑셀입력만 있었던 것 같기는 한데.. 다시 한번 찾아보지요.

**Comment by kalipso** [comment]
커밋했습니다. 무식하게 UPPER로 떡칠..나중에 성능 문제 생기면 수정하도록 하지요. 커밋 로그(메시지)는 잘못 입력했으니 소스만 확인하고 UPDATE하시면 됩니다.
