### ISSUE TITLE
B2EN_SC_SQL_TEXT_RST 입력 시 line 오류

### ISSUE THREAD

**Issue by kalipso** [wjjeong/SQLCV#6]
SQL 컨버전 후 아래 각 테이블을 쿼리해보면 
 * B2EN_SC_SQL_TEXT는 1~6이 입력됨
 * B2EN_SC_SQL_TEXT_RST 는 2~6이 입력됨

----------------------------------------
아래 테이블별 결과
----------------------------------------

[B2EN_SC_SQL_TEXT]
1	select
2	 *
3	from
4	 cm_gvof_hs
5	where
6	 gvof_cd = 'P014231'

[B2EN_SC_SQL_TEXT_RST]
2	select *
3	from
4	 CM_GVOF_CHG_HS
5	where
6	 GVOF_CD = 'P014231'

**Comment by wjjeong** [comment]
책임님 소스수정했습니다. 확인부탁드립니다~

**Comment by kalipso** [comment]
잘 되는 거 확인했음~
